# Copyright 2024-2026 Arran Ubels
# Distributed under the terms of the GNU General Public License v2
#
# Generated by: .github/workflows/app-misc-vhs-bin-update.yaml

EAPI=8

DESCRIPTION="Your CLI home video recorder 📼"
HOMEPAGE="https://github.com/charmbracelet/vhs/"
SRC_URI="
	amd64? (  https://github.com/charmbracelet/vhs/releases/download/v0.12.0/vhs_0.12.0_Linux_x86_64.tar.gz -> ${P}-vhs_${PV}_Linux_x86_64.tar.gz  )
	arm? (  https://github.com/charmbracelet/vhs/releases/download/v0.12.0/vhs_0.12.0_Linux_arm.tar.gz -> ${P}-vhs_${PV}_Linux_arm.tar.gz  )
	arm64? (  https://github.com/charmbracelet/vhs/releases/download/v0.12.0/vhs_0.12.0_Linux_arm64.tar.gz -> ${P}-vhs_${PV}_Linux_arm64.tar.gz  )
	x86? (  https://github.com/charmbracelet/vhs/releases/download/v0.12.0/vhs_0.12.0_Linux_i386.tar.gz -> ${P}-vhs_${PV}_Linux_i386.tar.gz  )
"
LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~arm ~arm64 ~x86"
IUSE=" doc man"

REQUIRED_USE=""

RDEPEND="media-video/ffmpeg www-apps/ttyd www-client/chromium "

S="${WORKDIR}"

src_unpack() {
  if use amd64; then
    unpack "${DISTDIR}/${P}-vhs_${PV}_Linux_x86_64.tar.gz" || die "Can't unpack archive file"
  fi
  if use arm; then
    unpack "${DISTDIR}/${P}-vhs_${PV}_Linux_arm.tar.gz" || die "Can't unpack archive file"
  fi
  if use arm64; then
    unpack "${DISTDIR}/${P}-vhs_${PV}_Linux_arm64.tar.gz" || die "Can't unpack archive file"
  fi
  if use x86; then
    unpack "${DISTDIR}/${P}-vhs_${PV}_Linux_i386.tar.gz" || die "Can't unpack archive file"
  fi
  if use man; then
    if use amd64; then
      gzip -d "vhs_${PV}_Linux_x86_64/manpages/vhs.1.gz" || die "Failed to decompress manual page vhs.1"
    fi
    if use arm; then
      gzip -d "vhs_${PV}_Linux_arm/manpages/vhs.1.gz" || die "Failed to decompress manual page vhs.1"
    fi
    if use arm64; then
      gzip -d "vhs_${PV}_Linux_arm64/manpages/vhs.1.gz" || die "Failed to decompress manual page vhs.1"
    fi
    if use x86; then
      gzip -d "vhs_${PV}_Linux_i386/manpages/vhs.1.gz" || die "Failed to decompress manual page vhs.1"
    fi
  fi
}

src_install() {
  exeinto /opt/bin
  if use amd64; then
    newexe "vhs_${PV}_Linux_x86_64/vhs" "vhs" || die "Failed to install Binary"
  fi
  if use arm; then
    newexe "vhs_${PV}_Linux_arm/vhs" "vhs" || die "Failed to install Binary"
  fi
  if use arm64; then
    newexe "vhs_${PV}_Linux_arm64/vhs" "vhs" || die "Failed to install Binary"
  fi
  if use x86; then
    newexe "vhs_${PV}_Linux_i386/vhs" "vhs" || die "Failed to install Binary"
  fi
  if use man; then
    if use amd64; then
      newman "vhs_${PV}_Linux_x86_64/manpages/vhs.1" "vhs.1" || die "Failed to install manual page vhs.1"
    fi
    if use arm; then
      newman "vhs_${PV}_Linux_arm/manpages/vhs.1" "vhs.1" || die "Failed to install manual page vhs.1"
    fi
    if use arm64; then
      newman "vhs_${PV}_Linux_arm64/manpages/vhs.1" "vhs.1" || die "Failed to install manual page vhs.1"
    fi
    if use x86; then
      newman "vhs_${PV}_Linux_i386/manpages/vhs.1" "vhs.1" || die "Failed to install manual page vhs.1"
    fi
  fi
  if use doc; then
    if use amd64; then
      newdoc "vhs_${PV}_Linux_x86_64/LICENSE" "LICENSE" || die "Failed to install document LICENSE"
      newdoc "vhs_${PV}_Linux_x86_64/README.md" "README.md" || die "Failed to install document README.md"
    fi
    if use arm; then
      newdoc "vhs_${PV}_Linux_arm/LICENSE" "LICENSE" || die "Failed to install document LICENSE"
      newdoc "vhs_${PV}_Linux_arm/README.md" "README.md" || die "Failed to install document README.md"
    fi
    if use arm64; then
      newdoc "vhs_${PV}_Linux_arm64/LICENSE" "LICENSE" || die "Failed to install document LICENSE"
      newdoc "vhs_${PV}_Linux_arm64/README.md" "README.md" || die "Failed to install document README.md"
    fi
    if use x86; then
      newdoc "vhs_${PV}_Linux_i386/LICENSE" "LICENSE" || die "Failed to install document LICENSE"
      newdoc "vhs_${PV}_Linux_i386/README.md" "README.md" || die "Failed to install document README.md"
    fi
  fi
}
