# Copyright 2024-2026 Arran Ubels
# Distributed under the terms of the GNU General Public License v2
#
# Generated by: .github/workflows/app-misc-vhs-bin-update.yaml

EAPI=8

DESCRIPTION="Your CLI home video recorder 📼"
HOMEPAGE="https://github.com/charmbracelet/vhs/"
SRC_URI="
	amd64? (  https://github.com/charmbracelet/vhs/releases/download/v0.12.0/${PV} -> vhs-bin-0.12.0-vhs_0.12.0_Linux_x86_64.tar.gz  )
"
LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64"
IUSE=" doc"

REQUIRED_USE=""

RDEPEND="media-video/ffmpeg www-apps/ttyd "

S="${WORKDIR}"

src_unpack() {
  if use amd64; then
    unpack "${DISTDIR}/${P}-vhs_${PV}_Linux_x86_64.tar.gz" || die "Can't unpack archive file"
  fi
}

src_install() {
  exeinto /opt/bin
  if use amd64; then
    newexe "vhs_${PV}_Linux_x86_64/vhs" "vhs" || die "Failed to install Binary"
  fi
  if use doc; then
    if use amd64; then
      newdoc "vhs_${PV}_Linux_x86_64/LICENSE" "LICENSE" || die "Failed to install document LICENSE"
      newdoc "vhs_${PV}_Linux_x86_64/README.md" "README.md" || die "Failed to install document README.md"
    fi
  fi
  dosym /opt/bin/vhs /usr/bin/vhs
}
