#!/usr/bin/env python3
"""Regenerate the pinned Dart DEPS source graph in the ebuild.

The input is the DEPS file from the upstream Dart SDK tag named by
SDK_VERSION.  Conditions are evaluated for the only supported build:
Linux/amd64, using the system compiler, GN, Ninja, and C library.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys
import tempfile
import urllib.request


SDK_VERSION = "3.13.3"
BOOTSTRAP_SDK_TAG = "version:3.13.0-103.1.beta"
SDK_ARCHIVE = (
    "https://github.com/dart-lang/sdk/archive/refs/tags/"
    f"{SDK_VERSION}.tar.gz"
)
SDK_DEPS_URL = (
    "https://raw.githubusercontent.com/dart-lang/sdk/"
    f"{SDK_VERSION}/DEPS"
)
EBUILD = Path(__file__).parents[1] / f"dart-{SDK_VERSION}-r1.ebuild"
BEGIN = "# BEGIN GENERATED BY files/generate-ebuild.py"
END = "# END GENERATED BY files/generate-ebuild.py"

# These active CIPD entries are deliberately not materialized as sources.
# Any new active entry makes regeneration fail until its build relevance is
# audited and documented here.
REVIEWED_CIPD = {
    "sdk/tools/sdks/dart-sdk": "provided by dev-lang/dart-bootstrap-bin",
    "sdk/third_party/d8/linux/x64": "JavaScript-engine tests only",
    "sdk/third_party/d8/linux/arm64": "JavaScript-engine tests only",
    "sdk/third_party/d8/macos/x64": "JavaScript-engine tests only",
    "sdk/third_party/d8/macos/arm64": "JavaScript-engine tests only",
    "sdk/third_party/d8/windows/x64": "JavaScript-engine tests only",
    "sdk/third_party/devtools": (
        "replaced by the pinned devtools_shared source package"
    ),
    "sdk/tests/co19/src": "language conformance tests only",
    "sdk/third_party/gsutil": "release-bot upload helper only",
    "sdk/buildtools/sysroot/linux": "system root selected by --no-clang",
    "sdk/buildtools/sysroot/focal": "riscv64 sysroot; amd64-only package",
    "sdk/buildtools/linux-x64/clang": "system GCC selected by --no-clang",
    "sdk/buildtools/reclient-linux": "remote execution disabled",
    "sdk/buildtools": "provided by dev-build/gn",
    "sdk/buildtools/ninja": "provided by dev-build/ninja",
    "sdk/benchmarks/NativeCall/native/out/": "benchmark fixture only",
    "sdk/benchmarks/FfiBoringssl/native/out/": "benchmark fixture only",
    "sdk/benchmarks/FfiCall/native/out/": "benchmark fixture only",
    "sdk/pkg/front_end/test/types/benchmark_data": "test fixture only",
}

# Active DEPS entries that are unrelated to an amd64 create_sdk build.  Like
# REVIEWED_CIPD, this is intentionally exact so upstream changes fail closed.
REVIEWED_GIT = {
    "sdk/buildtools/clang_format/script": "source-formatting helper only",
    "sdk/third_party/jinja2": "DOM generator and VM wiki tooling only",
    "sdk/third_party/libc": "unused with the system GCC/libstdc++ toolchain",
    "sdk/third_party/libcxx": "unused with the system GCC/libstdc++ toolchain",
    "sdk/third_party/libcxxabi": "unused with the system GCC/libstdc++ toolchain",
    "sdk/third_party/markupsafe": "Jinja dependency only",
    "sdk/third_party/ply": "legacy DOM generator only",
}

GITHUB_ORGS = {
    "https://github.com/WebAssembly": "WEBASSEMBLY_GITHUB",
    "https://github.com/dart-lang": "DART_GITHUB",
    "https://github.com/emscripten-core": "EMSCRIPTEN_GITHUB",
    "https://github.com/flutter": "FLUTTER_GITHUB",
    "https://github.com/google": "GOOGLE_GITHUB",
    "https://github.com/gsource-mirror": "GSOURCE_GITHUB",
    "https://github.com/librepo": "LIBREPO_GITHUB",
    "https://github.com/mdn": "MDN_GITHUB",
    "https://github.com/simolus3": "SIMOLUS_GITHUB",
}

SHORT_NAMES = {
    "browser-compat-data": "BROWSER_DATA",
    "clang-format": "CLANG_FORMAT",
    "chromium-src-third_party-zlib": "ZLIB",
    "chromium-icu": "ICU",
    "cpu_features": "CPU_FEATURES",
    "dart_style": "DART_STYLE",
    "devtools": "DEVTOOLS_SHARED",
    "leak_tracker": "LEAK_TRACKER",
    "protobuf.dart": "PROTOBUF",
    "sync_http": "SYNC_HTTP",
    "sync_http.dart": "SYNC_HTTP",
    "vector_math.dart": "VECTOR_MATH",
    "webdriver.dart": "WEBDRIVER",
    "webkit_inspection_protocol.dart": "WEBKIT_PROTOCOL",
}


def load_deps(path: Path) -> dict[str, object]:
    """Evaluate the data-only DEPS DSL without exposing Python builtins."""
    namespace: dict[str, object] = {
        "__builtins__": {},
        "linux": "linux",
        "mac": "mac",
        "win": "win",
        "android": "android",
    }

    def var(name: str) -> object:
        return namespace["vars"][name]  # type: ignore[index]

    namespace["Var"] = var
    exec(compile(path.read_text(), str(path), "exec"), namespace)
    variables = namespace["vars"]
    assert isinstance(variables, dict)
    variables.update(
        {
            "build_devtools_from_sources": False,
            "download_reclient": False,
        }
    )
    return namespace


def condition_is_true(condition: str | None, variables: dict[str, object]) -> bool:
    if not condition:
        return True
    values = {
        **variables,
        "host_os": "linux",
        "host_cpu": "x64",
        "checkout_linux": True,
        "checkout_mac": False,
        "checkout_win": False,
        "checkout_android": False,
        "linux": "linux",
        "mac": "mac",
        "win": "win",
        "android": "android",
    }
    return bool(eval(condition, {"__builtins__": {}}, values))


def active_dependencies(namespace: dict[str, object]) -> list[tuple[str, object]]:
    variables = namespace["vars"]
    assert isinstance(variables, dict)
    dependencies = dict(namespace["deps"])  # type: ignore[arg-type]
    deps_os = namespace.get("deps_os", {})
    if isinstance(deps_os, dict):
        dependencies.update(deps_os.get("linux", {}))

    active = []
    for destination, dependency in dependencies.items():
        condition = dependency.get("condition") if isinstance(dependency, dict) else None
        if condition_is_true(condition, variables):
            active.append((str(destination), dependency))
    return sorted(active)


def git_source(
    destination: str,
    dependency: object,
) -> tuple[str, str, str, str, str, int]:
    url = dependency.get("url") if isinstance(dependency, dict) else dependency
    if not isinstance(url, str) or "@" not in url:
        raise ValueError(f"unsupported Git DEPS entry at {destination}: {dependency!r}")
    repository, revision = url.rsplit("@", 1)
    repository = stable_github_repository(repository.removesuffix(".git"))
    relative = destination.removeprefix("sdk/")
    repository_name = repository.rstrip("/").rsplit("/", 1)[-1]
    name = SHORT_NAMES.get(repository_name)
    if name is None:
        name = re.sub(r"[^A-Za-z0-9]+", "_", repository_name).strip("_").upper()
    filename = f"dart-dep-{name.lower().replace('_', '-')}-{revision[:8]}.tar.gz"
    return repository, revision, filename, relative, ".", 1


def stable_github_repository(repository: str) -> str:
    """Return a content-addressed GitHub mirror with stable archive bytes."""
    external_prefixes = (
        "https://chromium.googlesource.com/external/github.com/",
        "https://dart.googlesource.com/external/github.com/",
    )
    for prefix in external_prefixes:
        if repository.startswith(prefix):
            return "https://github.com/" + repository.removeprefix(prefix)

    mirrors = {
        "https://boringssl.googlesource.com/boringssl": (
            "https://github.com/google/boringssl"
        ),
        "https://chromium.googlesource.com/chromium/deps/icu": (
            "https://github.com/librepo/chromium-icu"
        ),
        "https://chromium.googlesource.com/chromium/src/third_party/zlib": (
            "https://github.com/gsource-mirror/chromium-src-third_party-zlib"
        ),
        "https://dart.googlesource.com/protobuf": (
            "https://github.com/google/protobuf.dart"
        ),
        "https://dart.googlesource.com/sync_http": (
            "https://github.com/google/sync_http.dart"
        ),
        "https://dart.googlesource.com/webcore": (
            "https://github.com/dart-archive/webcore"
        ),
    }
    if repository in mirrors:
        return mirrors[repository]

    dart_prefix = "https://dart.googlesource.com/"
    if repository.startswith(dart_prefix):
        return "https://github.com/dart-lang/" + repository.removeprefix(
            dart_prefix
        )

    raise ValueError(f"no stable archive mirror for {repository}")


def render(deps_path: Path) -> str:
    namespace = load_deps(deps_path)
    variables = namespace["vars"]
    assert isinstance(variables, dict)
    if variables.get("sdk_tag") != BOOTSTRAP_SDK_TAG:
        raise ValueError(
            "Dart bootstrap changed: "
            f"expected {BOOTSTRAP_SDK_TAG!r}, got {variables.get('sdk_tag')!r}"
        )
    git_sources: list[tuple[str, str, str, str, str, int]] = []
    active_cipd: dict[str, str] = {}
    excluded_git: dict[str, str] = {}

    for destination, dependency in active_dependencies(namespace):
        dep_type = dependency.get("dep_type", "git") if isinstance(dependency, dict) else "git"
        if dep_type == "cipd":
            active_cipd[destination] = REVIEWED_CIPD.get(destination, "")
            if destination == "sdk/third_party/devtools":
                revision = str(variables["devtools_rev"])
                git_sources.append(
                    (
                        "https://github.com/flutter/devtools",
                        revision,
                        f"dart-dep-devtools-shared-{revision[:8]}.tar.gz",
                        "third_party/devtools/devtools_shared",
                        "packages/devtools_shared",
                        3,
                    )
                )
        elif dep_type == "git":
            if destination in REVIEWED_GIT:
                excluded_git[destination] = REVIEWED_GIT[destination]
            else:
                git_sources.append(git_source(destination, dependency))
        else:
            raise ValueError(f"unsupported DEPS type {dep_type!r} at {destination}")

    missing_review = sorted(path for path, reason in active_cipd.items() if not reason)
    stale_review = sorted(set(REVIEWED_CIPD) - set(active_cipd))
    if missing_review or stale_review:
        raise ValueError(
            "CIPD audit is out of date; "
            f"unreviewed={missing_review}, no-longer-active={stale_review}"
        )
    stale_git_review = sorted(set(REVIEWED_GIT) - set(excluded_git))
    if stale_git_review:
        raise ValueError(
            "Git exclusion audit is out of date; "
            f"no-longer-active={stale_git_review}"
        )

    identifiers: dict[str, tuple[str, str, str, str, str, int]] = {}
    for source in git_sources:
        repository, _, _, _, _, _ = source
        repository_name = repository.rstrip("/").rsplit("/", 1)[-1]
        identifier = SHORT_NAMES.get(repository_name)
        if identifier is None:
            identifier = re.sub(
                r"[^A-Za-z0-9]+", "_", repository_name
            ).strip("_").upper()
        if identifier in identifiers:
            raise ValueError(f"duplicate source identifier {identifier}")
        identifiers[identifier] = source

    lines = [BEGIN, 'GITHUB="https://github.com"']
    for base, identifier in GITHUB_ORGS.items():
        suffix = base.removeprefix("https://github.com")
        lines.append(f'{identifier}="${{GITHUB}}{suffix}"')
    lines.extend(['SDK_GIT="${DART_GITHUB}/sdk"', ""])
    for identifier, source in sorted(identifiers.items()):
        repository, revision, _, _, _, _ = source
        rendered_repository = repository
        substitutions = {
            base: f"${{{name}}}" for base, name in GITHUB_ORGS.items()
        }
        for base in sorted(substitutions, key=len, reverse=True):
            if rendered_repository.startswith(base):
                rendered_repository = substitutions[base] + rendered_repository[len(base):]
                break
        lines.append(f'{identifier}_GIT="{rendered_repository}"')
        lines.append(f'{identifier}_REV="{revision}"')

    lines.extend(["", "DART_DEPENDENCY_ARCHIVES=("])
    for identifier, source in sorted(identifiers.items()):
        _, _, filename, destination, member, strip = source
        lines.append(f'\t"{destination}"')
        lines.append(f'\t"{filename}"')
        lines.append(f'\t"{member}"')
        lines.append(f'\t"{strip}"')
    lines.extend([")", "", 'SRC_URI="'])
    lines.append("\t${SDK_GIT}/archive/refs/tags/${PV}.tar.gz")
    lines.append("\t\t-> ${P}.tar.gz")
    for identifier, source in sorted(identifiers.items()):
        _, _, filename, _, _, _ = source
        lines.append(
            f"\t${{{identifier}_GIT}}/archive/${{{identifier}_REV}}.tar.gz"
        )
        lines.append(f"\t\t-> {filename}")
    lines.extend(['"', END])
    too_long = [(index, line) for index, line in enumerate(lines, 1) if len(line.expandtabs(8)) > 80]
    if too_long:
        raise ValueError(f"generated lines exceed 80 columns: {too_long}")
    return "\n".join(lines)


def obtain_deps(sdk_tree: Path | None) -> tuple[Path, tempfile.TemporaryDirectory[str] | None]:
    if sdk_tree is not None:
        return sdk_tree / "DEPS", None

    temporary = tempfile.TemporaryDirectory(prefix="dart-deps-")
    deps_path = Path(temporary.name) / "DEPS"
    urllib.request.urlretrieve(SDK_DEPS_URL, deps_path)
    return deps_path, temporary


def update_ebuild(generated: str, check: bool) -> int:
    existing = EBUILD.read_text()
    pattern = re.compile(
        rf"^{re.escape(BEGIN)}$.*?^{re.escape(END)}$",
        re.MULTILINE | re.DOTALL,
    )
    replacement, count = pattern.subn(generated, existing)
    if count != 1:
        raise ValueError(f"expected one generated block in {EBUILD}, found {count}")
    if replacement == existing:
        return 0
    if check:
        print(f"{EBUILD} is not synchronized with Dart {SDK_VERSION} DEPS", file=sys.stderr)
        return 1
    EBUILD.write_text(replacement)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--sdk-tree", type=Path)
    args = parser.parse_args()
    deps_path, temporary = obtain_deps(args.sdk_tree)
    try:
        return update_ebuild(render(deps_path), args.check)
    finally:
        if temporary is not None:
            temporary.cleanup()


if __name__ == "__main__":
    raise SystemExit(main())
