# Copyright 2024-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Source graph generated by files/generate-ebuild.py.
# Build phases are maintained here.

EAPI=8

PYTHON_COMPAT=( python3_{12..15} )
inherit multiprocessing python-any-r1

DESCRIPTION="The Dart SDK, including the VM, compilers, and core libraries"
HOMEPAGE="https://dart.dev/ https://github.com/dart-lang/sdk"

# BEGIN GENERATED BY files/generate-ebuild.py
GITHUB="https://github.com"
WEBASSEMBLY_GITHUB="${GITHUB}/WebAssembly"
DART_GITHUB="${GITHUB}/dart-lang"
EMSCRIPTEN_GITHUB="${GITHUB}/emscripten-core"
FLUTTER_GITHUB="${GITHUB}/flutter"
GOOGLE_GITHUB="${GITHUB}/google"
GSOURCE_GITHUB="${GITHUB}/gsource-mirror"
LIBREPO_GITHUB="${GITHUB}/librepo"
MDN_GITHUB="${GITHUB}/mdn"
SIMOLUS_GITHUB="${GITHUB}/simolus3"
SDK_GIT="${DART_GITHUB}/sdk"

BINARYEN_GIT="${WEBASSEMBLY_GITHUB}/binaryen"
BINARYEN_REV="9926156a583cec3d22d521232b31c70fa9a87dc1"
BORINGSSL_GIT="${GOOGLE_GITHUB}/boringssl"
BORINGSSL_REV="2e508c973d634b3aa51b71db5062bc6b096e5031"
BROWSER_DATA_GIT="${MDN_GITHUB}/browser-compat-data"
BROWSER_DATA_REV="ac8cae697014da1ff7124fba33b0b4245cc6cd1b"
CORE_GIT="${DART_GITHUB}/core"
CORE_REV="be0b1531c445a185d3e93887b8d0355fc766c314"
CPU_FEATURES_GIT="${GOOGLE_GITHUB}/cpu_features"
CPU_FEATURES_REV="936b9ab5515dead115606559502e3864958f7f6e"
DARTDOC_GIT="${DART_GITHUB}/dartdoc"
DARTDOC_REV="1d56f263955f329b6701d8f84f069eb0aef353a4"
DART_STYLE_GIT="${DART_GITHUB}/dart_style"
DART_STYLE_REV="39edc2d946a5d7bd1caf6f1695f366b00f7b873c"
DEVTOOLS_SHARED_GIT="${FLUTTER_GITHUB}/devtools"
DEVTOOLS_SHARED_REV="12d595649f189f1896722623f72599077f476848"
ECOSYSTEM_GIT="${DART_GITHUB}/ecosystem"
ECOSYSTEM_REV="848b3bf3b757d2e9ae4d60030eeed5756c87783f"
EMSDK_GIT="${EMSCRIPTEN_GITHUB}/emsdk"
EMSDK_REV="e41b8c68a248da5f18ebd03bd0420953945d52ff"
HTTP_GIT="${DART_GITHUB}/http"
HTTP_REV="5d94ef52582867e077bf41c3fa20fb8b1d1d834e"
I18N_GIT="${DART_GITHUB}/i18n"
I18N_REV="d0683bdea253d19a4350f5bc2be9017aba61837f"
ICU_GIT="${LIBREPO_GITHUB}/chromium-icu"
ICU_REV="a86a32e67b8d1384b33f8fa48c83a6079b86f8cd"
LEAK_TRACKER_GIT="${DART_GITHUB}/leak_tracker"
LEAK_TRACKER_REV="f5620600a5ce1c44f65ddaa02001e200b096e14c"
NATIVE_GIT="${DART_GITHUB}/native"
NATIVE_REV="d51c53334486af69435b0b45c4bdfe303a830170"
PERFETTO_GIT="${GOOGLE_GITHUB}/perfetto"
PERFETTO_REV="13ce0c9e13b0940d2476cd0cff2301708a9a2e2b"
PROTOBUF_GIT="${GOOGLE_GITHUB}/protobuf.dart"
PROTOBUF_REV="84079e8b8531309e06ba7276b1c28bdca9210ad6"
PUB_GIT="${DART_GITHUB}/pub"
PUB_REV="ec276d10a7fa0f6c6ec005340fb9ad29f3b012d0"
SHELF_GIT="${DART_GITHUB}/shelf"
SHELF_REV="71248e727317930f244c4b4535e9733bcfc66677"
SYNC_HTTP_GIT="${GOOGLE_GITHUB}/sync_http.dart"
SYNC_HTTP_REV="6666fff944221891182e1f80bf56569338164d72"
TAR_GIT="${SIMOLUS_GITHUB}/tar"
TAR_REV="13479f7c2a18f499e840ad470cfcca8c579f6909"
TEST_GIT="${DART_GITHUB}/test"
TEST_REV="bd92e633e7f05edc3301865bdc00d1ae181cb1f1"
TOOLS_GIT="${DART_GITHUB}/tools"
TOOLS_REV="7fec8be9af0cd0367d03dbec29b66b3f46565720"
VECTOR_MATH_GIT="${GOOGLE_GITHUB}/vector_math.dart"
VECTOR_MATH_REV="cf3b5db7340d317dd3489e5a35434b408020a852"
WEB_GIT="${DART_GITHUB}/web"
WEB_REV="eb8c3fc61a1e35f48f865836c7c7342897d91bcc"
WEBCORE_GIT="https://github.com/dart-archive/webcore"
WEBCORE_REV="bcb10901266c884e7b3740abc597ab95373ab55c"
WEBDRIVER_GIT="${GOOGLE_GITHUB}/webdriver.dart"
WEBDRIVER_REV="3a711ebb36871eac997c5d5d2429f7414873dc63"
WEBKIT_PROTOCOL_GIT="${GOOGLE_GITHUB}/webkit_inspection_protocol.dart"
WEBKIT_PROTOCOL_REV="762115a971d1968bc940454ad1e88d506d8c5640"
ZLIB_GIT="${GSOURCE_GITHUB}/chromium-src-third_party-zlib"
ZLIB_REV="3008c4b3a06bd65392c31db8846000a21e3d03c5"

DART_DEPENDENCY_ARCHIVES=(
	"third_party/binaryen/src"
	"dart-dep-binaryen-9926156a.tar.gz"
	"."
	"1"
	"third_party/boringssl/src"
	"dart-dep-boringssl-2e508c97.tar.gz"
	"."
	"1"
	"third_party/mdn/browser-compat-data/src"
	"dart-dep-browser-data-ac8cae69.tar.gz"
	"."
	"1"
	"third_party/pkg/core"
	"dart-dep-core-be0b1531.tar.gz"
	"."
	"1"
	"third_party/cpu_features/src"
	"dart-dep-cpu-features-936b9ab5.tar.gz"
	"."
	"1"
	"third_party/pkg/dartdoc"
	"dart-dep-dartdoc-1d56f263.tar.gz"
	"."
	"1"
	"third_party/pkg/dart_style"
	"dart-dep-dart-style-39edc2d9.tar.gz"
	"."
	"1"
	"third_party/devtools/devtools_shared"
	"dart-dep-devtools-shared-12d59564.tar.gz"
	"packages/devtools_shared"
	"3"
	"third_party/pkg/ecosystem"
	"dart-dep-ecosystem-848b3bf3.tar.gz"
	"."
	"1"
	"third_party/emsdk"
	"dart-dep-emsdk-e41b8c68.tar.gz"
	"."
	"1"
	"third_party/pkg/http"
	"dart-dep-http-5d94ef52.tar.gz"
	"."
	"1"
	"third_party/pkg/i18n"
	"dart-dep-i18n-d0683bde.tar.gz"
	"."
	"1"
	"third_party/icu"
	"dart-dep-icu-a86a32e6.tar.gz"
	"."
	"1"
	"third_party/pkg/leak_tracker"
	"dart-dep-leak-tracker-f5620600.tar.gz"
	"."
	"1"
	"third_party/pkg/native"
	"dart-dep-native-d51c5333.tar.gz"
	"."
	"1"
	"third_party/perfetto/src"
	"dart-dep-perfetto-13ce0c9e.tar.gz"
	"."
	"1"
	"third_party/pkg/protobuf"
	"dart-dep-protobuf-84079e8b.tar.gz"
	"."
	"1"
	"third_party/pkg/pub"
	"dart-dep-pub-ec276d10.tar.gz"
	"."
	"1"
	"third_party/pkg/shelf"
	"dart-dep-shelf-71248e72.tar.gz"
	"."
	"1"
	"third_party/pkg/sync_http"
	"dart-dep-sync-http-6666fff9.tar.gz"
	"."
	"1"
	"third_party/pkg/tar"
	"dart-dep-tar-13479f7c.tar.gz"
	"."
	"1"
	"third_party/pkg/test"
	"dart-dep-test-bd92e633.tar.gz"
	"."
	"1"
	"third_party/pkg/tools"
	"dart-dep-tools-7fec8be9.tar.gz"
	"."
	"1"
	"third_party/pkg/vector_math"
	"dart-dep-vector-math-cf3b5db7.tar.gz"
	"."
	"1"
	"third_party/pkg/web"
	"dart-dep-web-eb8c3fc6.tar.gz"
	"."
	"1"
	"third_party/WebCore"
	"dart-dep-webcore-bcb10901.tar.gz"
	"."
	"1"
	"third_party/pkg/webdriver"
	"dart-dep-webdriver-3a711ebb.tar.gz"
	"."
	"1"
	"third_party/pkg/webkit_inspection_protocol"
	"dart-dep-webkit-protocol-762115a9.tar.gz"
	"."
	"1"
	"third_party/zlib"
	"dart-dep-zlib-3008c4b3.tar.gz"
	"."
	"1"
)

SRC_URI="
	${SDK_GIT}/archive/refs/tags/${PV}.tar.gz
		-> ${P}.tar.gz
	${BINARYEN_GIT}/archive/${BINARYEN_REV}.tar.gz
		-> dart-dep-binaryen-9926156a.tar.gz
	${BORINGSSL_GIT}/archive/${BORINGSSL_REV}.tar.gz
		-> dart-dep-boringssl-2e508c97.tar.gz
	${BROWSER_DATA_GIT}/archive/${BROWSER_DATA_REV}.tar.gz
		-> dart-dep-browser-data-ac8cae69.tar.gz
	${CORE_GIT}/archive/${CORE_REV}.tar.gz
		-> dart-dep-core-be0b1531.tar.gz
	${CPU_FEATURES_GIT}/archive/${CPU_FEATURES_REV}.tar.gz
		-> dart-dep-cpu-features-936b9ab5.tar.gz
	${DARTDOC_GIT}/archive/${DARTDOC_REV}.tar.gz
		-> dart-dep-dartdoc-1d56f263.tar.gz
	${DART_STYLE_GIT}/archive/${DART_STYLE_REV}.tar.gz
		-> dart-dep-dart-style-39edc2d9.tar.gz
	${DEVTOOLS_SHARED_GIT}/archive/${DEVTOOLS_SHARED_REV}.tar.gz
		-> dart-dep-devtools-shared-12d59564.tar.gz
	${ECOSYSTEM_GIT}/archive/${ECOSYSTEM_REV}.tar.gz
		-> dart-dep-ecosystem-848b3bf3.tar.gz
	${EMSDK_GIT}/archive/${EMSDK_REV}.tar.gz
		-> dart-dep-emsdk-e41b8c68.tar.gz
	${HTTP_GIT}/archive/${HTTP_REV}.tar.gz
		-> dart-dep-http-5d94ef52.tar.gz
	${I18N_GIT}/archive/${I18N_REV}.tar.gz
		-> dart-dep-i18n-d0683bde.tar.gz
	${ICU_GIT}/archive/${ICU_REV}.tar.gz
		-> dart-dep-icu-a86a32e6.tar.gz
	${LEAK_TRACKER_GIT}/archive/${LEAK_TRACKER_REV}.tar.gz
		-> dart-dep-leak-tracker-f5620600.tar.gz
	${NATIVE_GIT}/archive/${NATIVE_REV}.tar.gz
		-> dart-dep-native-d51c5333.tar.gz
	${PERFETTO_GIT}/archive/${PERFETTO_REV}.tar.gz
		-> dart-dep-perfetto-13ce0c9e.tar.gz
	${PROTOBUF_GIT}/archive/${PROTOBUF_REV}.tar.gz
		-> dart-dep-protobuf-84079e8b.tar.gz
	${PUB_GIT}/archive/${PUB_REV}.tar.gz
		-> dart-dep-pub-ec276d10.tar.gz
	${SHELF_GIT}/archive/${SHELF_REV}.tar.gz
		-> dart-dep-shelf-71248e72.tar.gz
	${SYNC_HTTP_GIT}/archive/${SYNC_HTTP_REV}.tar.gz
		-> dart-dep-sync-http-6666fff9.tar.gz
	${TAR_GIT}/archive/${TAR_REV}.tar.gz
		-> dart-dep-tar-13479f7c.tar.gz
	${TEST_GIT}/archive/${TEST_REV}.tar.gz
		-> dart-dep-test-bd92e633.tar.gz
	${TOOLS_GIT}/archive/${TOOLS_REV}.tar.gz
		-> dart-dep-tools-7fec8be9.tar.gz
	${VECTOR_MATH_GIT}/archive/${VECTOR_MATH_REV}.tar.gz
		-> dart-dep-vector-math-cf3b5db7.tar.gz
	${WEB_GIT}/archive/${WEB_REV}.tar.gz
		-> dart-dep-web-eb8c3fc6.tar.gz
	${WEBCORE_GIT}/archive/${WEBCORE_REV}.tar.gz
		-> dart-dep-webcore-bcb10901.tar.gz
	${WEBDRIVER_GIT}/archive/${WEBDRIVER_REV}.tar.gz
		-> dart-dep-webdriver-3a711ebb.tar.gz
	${WEBKIT_PROTOCOL_GIT}/archive/${WEBKIT_PROTOCOL_REV}.tar.gz
		-> dart-dep-webkit-protocol-762115a9.tar.gz
	${ZLIB_GIT}/archive/${ZLIB_REV}.tar.gz
		-> dart-dep-zlib-3008c4b3.tar.gz
"
# END GENERATED BY files/generate-ebuild.py

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64"

RDEPEND="!dev-lang/dart-bin"
BDEPEND="${PYTHON_DEPS}
	dev-build/gn
	dev-build/ninja
	=dev-lang/dart-bootstrap-bin-3.13.0_beta103_p1-r0:3.13
"

PATCHES=( "${FILESDIR}/${P}-no-prebuilt-devtools.patch" )

src_unpack() {
	unpack "dart-${PV}.tar.gz"
	mv "sdk-${PV}" "${S}" || die

	local archive destination index member strip
	for (( index = 0; index < ${#DART_DEPENDENCY_ARCHIVES[@]}; index += 4 )); do
		destination=${DART_DEPENDENCY_ARCHIVES[index]}
		archive=${DART_DEPENDENCY_ARCHIVES[index + 1]}
		member=${DART_DEPENDENCY_ARCHIVES[index + 2]}
		strip=${DART_DEPENDENCY_ARCHIVES[index + 3]}
		mkdir -p "${S}/${destination}" || die
		cd "${S}/${destination}" || die
		if [[ ${member} == . ]]; then
			tar -xf "${DISTDIR}/${archive}" \
				--strip-components="${strip}" || die
		else
			tar -xf "${DISTDIR}/${archive}" \
				--strip-components="${strip}" \
				--wildcards "*/${member}/*" || die
		fi
	done
}

src_prepare() {
	default
	python_setup

	# These files are normally created by gclient hooks.  Generate them with
	# the declared bootstrap compiler, forcing pub to resolve local DEPS only.
	mkdir -p build/config buildtools/ninja || die
	printf '%s\n' \
		'declare_args() {' \
		'  build_devtools_from_sources = false' \
		'}' \
		> build/config/gclient_args.gni || die
	ln -s "/opt/dart-bootstrap-3.13.0-103.1.beta" \
		tools/sdks/dart-sdk || die
	_PUB_TEST_SDK_VERSION=${PV} tools/sdks/dart-sdk/bin/dart \
		pub get --offline || die
	"${EPYTHON}" tools/generate_sdk_version_file.py || die

	ln -s "${BROOT}/usr/bin/gn" buildtools/gn || die
	ln -s "${BROOT}/usr/bin/ninja" buildtools/ninja/ninja || die
}

src_compile() {
	# --no-clang selects the native system toolchain and, consequently, no
	# downloaded Dart sysroot.  This package intentionally supports native
	# amd64 builds only.
	./tools/build.py \
		--arch x64 \
		--mode release \
		--no-clang \
		--no-git-version \
		--no-verify-sdk-hash \
		-j "$(makeopts_jobs)" \
		create_sdk || die
}

src_install() {
	dodir /opt/dart-sdk
	cp -a out/ReleaseX64/dart-sdk/. "${ED}/opt/dart-sdk/" || die
	dosym ../dart-sdk/bin/dart /opt/bin/dart
}
