name: dev-vcs/kgithub-notify update

permissions:
  contents: write

on:
  schedule:
    - cron: '20 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/dev-vcs-kgithub-notify-update.yaml'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  ecn: dev-vcs
  epn: kgithub-notify
  description: "A sleek GitHub notification system tray application written natively in C++ using Qt6 and KDE Frameworks 6"
  homepage: "https://github.com/arran4/kgithub-notify"
  github_owner: arran4
  github_repo: kgithub-notify
  keywords: ~amd64 ~x86
  workflow_filename: dev-vcs-kgithub-notify-update.yaml

jobs:
  check-and-create-ebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install g2
        uses: arran4/g2-action@v1.2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install required tools
        run: |
            sudo apt-get update
            sudo apt-get install -y wget jq coreutils

      - name: Process each release
        id: process_releases
        run: |
          ebuild_dir="./${{ env.ecn }}/${{ env.epn }}"
          mkdir -p "$ebuild_dir"
          local -A releaseTypes=()
          local tags; tags=$(curl -s  --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/${{ env.github_owner }}/${{ env.github_repo }}/releases | jq -r '.[]? | select(type=="object" and has("tag_name")) | .tag_name')
          # shellcheck disable=SC2086
          for tag in $tags; do
            version="${tag#v}"
            if [ "${version}" = "${tag}" ]; then
                echo "$version == $tag so there is no v removed skipping"
                continue
            fi
            # shellcheck disable=SC2034
            originalVersion="${version}"
            if ! echo "${version}" | grep -E '^([0-9]+)\.([0-9]+)(\.([0-9]+))?(-r[0-9]+)?((_)(alpha|beta|rc|p)[0-9]*)*$'; then
                echo "tag / $version doesn't match regexp";
                continue;
            fi
            local releaseType; releaseType="$(echo "${version}" | sed -n 's/^[^_]\+_\(alpha\|beta\|rc\|p[0-9]*\).*$/\1/p')"
            if [[ ! -v releaseTypes[${releaseType:=release}] ]]; then
                if [[ -v releaseTypes[release] ]]; then
                  echo "Already have a newer main release: ${releaseTypes[release]}"
                  continue
                fi
                releaseTypes[${releaseType:=release}]="${version}"
            else
                echo "Already have a newer ${releaseType:=release} release: ${releaseTypes[${releaseType:=release}]}"
                continue
            fi
            ebuild_file="${ebuild_dir}/${{ env.epn }}-${version}.ebuild"
            if [ ! -f "$ebuild_file" ]; then

              # shellcheck disable=SC2016
              {
                echo '# Manually maintained ebuild logic.'
                echo 'EAPI=8'
                echo ''
                echo 'KFMIN=6.0.0'
                echo 'QTMIN=6.6.2'
                echo 'ECM_TEST="true"'
                echo 'inherit ecm'
                echo "DESCRIPTION=\"${{ env.description }}\""
                echo "HOMEPAGE=\"${{ env.homepage }}\""
                echo 'SRC_URI="https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz"'
                echo ''
                echo 'LICENSE="BSD"'
                echo 'SLOT="0"'
                echo 'KEYWORDS="${{ env.keywords }}"'
                echo ''
                echo 'RDEPEND="'
                echo '	>=dev-qt/qtbase-${QTMIN}:6[gui,network,widgets,dbus]'
                echo '	>=dev-qt/qtsvg-${QTMIN}:6'
                echo '	>=kde-frameworks/kcoreaddons-${KFMIN}:6'
                echo '	>=kde-frameworks/kconfigwidgets-${KFMIN}:6'
                echo '	>=kde-frameworks/kxmlgui-${KFMIN}:6'
                echo '	>=kde-frameworks/kwallet-${KFMIN}:6'
                echo '	>=kde-frameworks/knotifications-${KFMIN}:6'
                echo '	>=kde-frameworks/ki18n-${KFMIN}:6'
                echo '	dev-libs/qtkeychain[qt6(+)]:='
                echo '"'
                echo 'DEPEND="${RDEPEND}'
                echo '	test? ( >=dev-qt/qtbase-${QTMIN}:6[test] )'
                echo '"'
                echo 'BDEPEND="'
                echo '	>=kde-frameworks/extra-cmake-modules-${KFMIN}:0'
                echo '	dev-qt/qttools:6'
                echo '"'
              } > $ebuild_file

              # Manifest generation

              g2 manifest upsert-from-url "https://github.com/${{ env.github_owner }}/${{ env.github_repo }}/archive/refs/tags/${tag}.tar.gz" "${{ env.epn }}-${version}.tar.gz" "${ebuild_dir}/Manifest"
              echo "generated_tag=${tag}" >> $GITHUB_OUTPUT
            fi
          done

      - name: Create Pull Request
        if: steps.process_releases.outputs.generated_tag
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Add ebuilds for new ${{ env.epn }} releases tag ${{ steps.process_releases.outputs.generated_tag }}"
          title: "Update ${{ env.epn }} to ${{ steps.process_releases.outputs.generated_tag }}"
          body: "This PR updates ${{ env.epn }} to the latest release ${{ steps.process_releases.outputs.generated_tag }}."
          branch: "update-${{ env.epn }}-${{ steps.process_releases.outputs.generated_tag }}"
          base: main
          labels: "automated pr"
