name: PR Checks

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  # Job to run static analysis (fast)
  pkgcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for commits check
      - name: Configure git remote
        run: git remote set-head origin -a
      - name: Run pkgcheck
        uses: pkgcore/pkgcheck-action@v1
        with:
          args: --keywords=-UnknownManifest --commits ${{ github.event.pull_request.base.ref && format('origin/{0}', github.event.pull_request.base.ref) || 'HEAD~1' }}

  g2-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: arran4/g2-action@v1.2
      - name: Run g2 lint
        run: |
          dirs=$(git diff --name-only origin/main HEAD | grep -E "^[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+/" | cut -d/ -f1,2 | sort -u || true)
          if [ -z "$dirs" ]; then
            echo "No package directories modified. Linting passed."
          else
            err=0
            for dir in $dirs; do
              echo "Linting $dir..."
              g2 lint "$dir" || err=$?
            done
            if [ $err -ne 0 ]; then
              /bin/false
            fi
          fi
