name: Regenerate All Cache

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  regenerate-cache:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
      options: --user root
    steps:
      - name: Install dependencies
        run: |
          mkdir -p /etc/portage
          echo 'ACCEPT_LICENSE="*"' > /etc/portage/make.conf
          echo 'FEATURES="-ipc-sandbox -network-sandbox -pid-sandbox"' >> /etc/portage/make.conf
          mkdir -p /var/db/repos/gentoo
          emerge-webrsync
          emerge --quiet app-portage/portage-utils dev-vcs/git net-misc/curl app-misc/jq dev-util/github-cli

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Overlay
        run: |
          mkdir -p /etc/portage/repos.conf
          cat > /etc/portage/repos.conf/arrans-overlay.conf << INNER_EOF
          [arrans-overlay]
          location = $(pwd)
          INNER_EOF

      - name: Run egencache update
        run: |
          egencache --repo=arrans-overlay --update

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add metadata/md5-cache metadata/md5-dict || true
          git config --global --add safe.directory "$(pwd)"

          if git diff --staged --quiet; then
            echo "No cache files to update."
          else
            git commit -m "chore: regenerate all cache"
            git push
          fi
